name: Run tests on private library repo

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch tests repo
        uses: actions/checkout@v3

      - name: Fetch noir-json-parser private repo
        run: |
          cd ../

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "machine github.com login grasshopper47 password ${{ secrets.PRIVATE_REPO_SECRET }}" > ~/.netrc

          git clone https://github.com/rontosoft/noir-json-parser.git lib

      - name: Install nargo 0.15.0
        run: |
          cd ../
          url="https://github.com/noir-lang/noir/releases/download/v0.15.0/nargo-x86_64-unknown-linux-gnu.tar.gz"
          curl -L "$url" | tar -xz -C .
          chmod +x nargo

      - name: Run nargo tests
        run: |
          ../nargo test --show-output
