name: Run tests on private library repo

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch `noir-json-parser-tests` repo
        uses: actions/checkout@v3

      - name: Fetch `noir-json-parser` private repo
        run: |
          cd ../

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "machine github.com login grasshopper47 password ${{ secrets.PRIVATE_REPO_SECRET }}" > ~/.netrc

          git clone https://github.com/rontosoft/noir-json-parser.git lib

      - name: Install nargo as indicated in project .toml file
        run: |
          cd ../lib

          # extract version from toml: take the line with version, split it by ", echo 2nd element from that array
          version=$(grep 'compiler_version[ ]*=[ ]*' Nargo.toml | awk -F '"' '{print $2}')

          cd ../

          url="https://github.com/noir-lang/noir/releases/download/v${version}/nargo-x86_64-unknown-linux-gnu.tar.gz"
          curl -L "$url" | tar -xz -C .
          chmod +x nargo

      - name: Run tests
        run: |
          ../nargo test --silence-warnings
